### ISSUE TITLE
DatabaseError [SequelizeDatabaseError]: SQLITE_CORRUPT: database disk image is malformed

### ISSUE THREAD

**Issue by arno01** [Akashlytics/akashlytics#41]
Hi, I'm getting this error when opening http://127.0.0.1:3000/ -> `DatabaseError [SequelizeDatabaseError]: SQLITE_CORRUPT: database disk image is malformed` (the error is in the logs below)

![image](https://user-images.githubusercontent.com/3791945/165298465-a53c2d9b-d318-4b42-a4ec-f14d523a58df.png)

```
arno@stealth:~/git/akashlytics$ docker-compose build
[+] Building 167.3s (21/21) FINISHED                                                                                                         
 => [baktun/akashlytics-web internal] load build definition from Dockerfile                                                             1.7s
 => => transferring dockerfile: 513B                                                                                                    0.0s
 => [baktun/akashlytics-api internal] load build definition from Dockerfile                                                             1.5s
 => => transferring dockerfile: 231B                                                                                                    0.1s
 => [baktun/akashlytics-web internal] load .dockerignore                                                                                2.0s
 => => transferring context: 72B                                                                                                        0.0s
 => [baktun/akashlytics-api internal] load .dockerignore                                                                                2.2s
 => => transferring context: 78B                                                                                                        0.0s
 => [baktun/akashlytics-api internal] load metadata for docker.io/library/node:14-alpine                                                0.0s
 => [baktun/akashlytics-web internal] load metadata for docker.io/library/nginx:stable-alpine                                           0.0s
 => [baktun/akashlytics-web build 1/5] FROM docker.io/library/node:14-alpine                                                            6.2s
 => [baktun/akashlytics-web internal] load build context                                                                                3.3s
 => => transferring context: 1.20MB                                                                                                     0.3s
 => [baktun/akashlytics-web stage-1 1/4] FROM docker.io/library/nginx:stable-alpine                                                     8.0s
 => [baktun/akashlytics-api internal] load build context                                                                                3.1s
 => => transferring context: 520.45kB                                                                                                   0.1s
 => [baktun/akashlytics-api build 2/5] WORKDIR /app                                                                                     1.8s
 => [baktun/akashlytics-web build 3/5] COPY . .                                                                                         0.9s
 => [baktun/akashlytics-api 3/5] COPY . .                                                                                               1.2s
 => [baktun/akashlytics-web build 4/5] RUN npm ci                                                                                     128.9s
 => [baktun/akashlytics-api 4/5] RUN npm ci                                                                                           130.1s
 => [baktun/akashlytics-web build 5/5] RUN npm run build                                                                               20.0s
 => [baktun/akashlytics-api 5/5] RUN npm run build                                                                                      8.4s
 => [baktun/akashlytics-web] exporting to image                                                                                        10.2s 
 => => exporting layers                                                                                                                 1.0s 
 => => writing image sha256:7261d4c7b33f936c4fb87ed4d27de9801e97ba388ee522b312dc98c54ebe4f07                                            0.0s 
 => => naming to docker.io/baktun/akashlytics-api                                                                                       0.0s 
 => => writing image sha256:532d657370111df3c1edb2137aafae3cc7cae7cb73665cc58fdc2b893201717a                                            0.0s 
 => => naming to docker.io/baktun/akashlytics-web                                                                                       0.0s 
 => [baktun/akashlytics-web stage-1 2/4] COPY --from=build /app/dist /usr/share/nginx/html                                              0.6s 
 => [baktun/akashlytics-web stage-1 3/4] COPY nginx.conf /etc/nginx/conf.d/default.conf                                                 0.7s 
 => [baktun/akashlytics-web stage-1 4/4] RUN sed -i "s|<API_BASE_URL>|http://localhost:3080|g" /etc/nginx/conf.d/default.conf           1.5s 
                                                                                                                                             
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

arno@stealth:~/git/akashlytics$ docker-compose up -d
[+] Running 3/3
 ⠿ Network akashlytics_default  Created                                                                                                 0.2s
 ⠿ Container akashlytics-web    Started                                                                                                 3.0s
 ⠿ Container akashlytics-api    Started      
```

## Logs

```
arno@stealth:~/git/akashlytics$ docker-compose ps
NAME                COMMAND                  SERVICE             STATUS              PORTS
akashlytics-api     "docker-entrypoint.s…"   api                 running             0.0.0.0:3080->3080/tcp, :::3080->3080/tcp
akashlytics-web     "/docker-entrypoint.…"   web                 running             0.0.0.0:3000->80/tcp, :::3000->80/tcp

arno@stealth:~/git/akashlytics$ docker-compose logs -f
akashlytics-web  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
akashlytics-api  | Downloading database files...
akashlytics-web  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
akashlytics-api  | server started at http://localhost:3080
akashlytics-web  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
akashlytics-web  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
akashlytics-web  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
akashlytics-web  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
akashlytics-web  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
akashlytics-web  | /docker-entrypoint.sh: Configuration complete; ready for start up
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: using the "epoll" event method
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: nginx/1.20.2
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424) 
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: OS: Linux 5.13.0-39-generic
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: start worker processes
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: start worker process 32
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: start worker process 33
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: start worker process 34
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: start worker process 35
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: start worker process 36
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: start worker process 37
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: start worker process 38
akashlytics-web  | 2022/04/26 12:02:20 [notice] 1#1: start worker process 39
akashlytics-web  | 172.19.0.1 - - [26/Apr/2022:12:02:40 +0000] "GET / HTTP/1.1" 200 1524 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
akashlytics-web  | 172.19.0.1 - - [26/Apr/2022:12:02:41 +0000] "GET /runtime.bundle.js?e86c0b9a42334293f48e HTTP/1.1" 200 3366 "http://127.0.0.1:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
akashlytics-web  | 172.19.0.1 - - [26/Apr/2022:12:02:41 +0000] "GET /334.bundle.js?e86c0b9a42334293f48e HTTP/1.1" 200 872193 "http://127.0.0.1:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
akashlytics-web  | 172.19.0.1 - - [26/Apr/2022:12:02:41 +0000] "GET /main.bundle.js?e86c0b9a42334293f48e HTTP/1.1" 200 61321 "http://127.0.0.1:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
akashlytics-web  | 172.19.0.1 - - [26/Apr/2022:12:02:41 +0000] "GET /131.bundle.js HTTP/1.1" 200 4158 "http://127.0.0.1:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
akashlytics-web  | 172.19.0.1 - - [26/Apr/2022:12:02:41 +0000] "GET /images/akashlytics_logo_compact.png HTTP/1.1" 200 10715 "http://127.0.0.1:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
akashlytics-web  | 172.19.0.1 - - [26/Apr/2022:12:02:41 +0000] "GET /images/powered-by-akash.png HTTP/1.1" 200 12673 "http://127.0.0.1:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
akashlytics-web  | 172.19.0.1 - - [26/Apr/2022:12:02:41 +0000] "GET /favicon/favicon-32x32.png HTTP/1.1" 200 1728 "http://127.0.0.1:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
akashlytics-api  | DatabaseError [SequelizeDatabaseError]: SQLITE_CORRUPT: database disk image is malformed
akashlytics-api  |     at Query.formatError (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16)
akashlytics-api  |     at Query._handleQueryResponse (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
akashlytics-api  |     at afterExecute (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27)
akashlytics-api  |     at Statement.errBack (/app/node_modules/sqlite3/lib/sqlite3.js:14:21)
akashlytics-api  |     at Statement.topLevelDomainCallback (domain.js:152:15)
akashlytics-api  |     at Statement.callbackTrampoline (internal/async_hooks.js:128:24) {
akashlytics-api  |   parent: [Error: SQLITE_CORRUPT: database disk image is malformed] {
akashlytics-api  |     errno: 11,
akashlytics-api  |     code: 'SQLITE_CORRUPT',
akashlytics-api  |     sql: 'SELECT `height`, `datetime`, `dayId`, `isProcessed`, `totalTxCount`, `totalUAktSpent`, `activeLeaseCount`, `totalLeaseCount`, `activeCPU`, `activeMemory`, `activeStorage`, `activeProviderCount`, `createdAt`, `updatedAt` FROM `block` AS `block` WHERE `block`.`isProcessed` = 1 ORDER BY `block`.`height` DESC LIMIT 1;'
akashlytics-api  |   },
akashlytics-api  |   original: [Error: SQLITE_CORRUPT: database disk image is malformed] {
akashlytics-api  |     errno: 11,
akashlytics-api  |     code: 'SQLITE_CORRUPT',
akashlytics-api  |     sql: 'SELECT `height`, `datetime`, `dayId`, `isProcessed`, `totalTxCount`, `totalUAktSpent`, `activeLeaseCount`, `totalLeaseCount`, `activeCPU`, `activeMemory`, `activeStorage`, `activeProviderCount`, `createdAt`, `updatedAt` FROM `block` AS `block` WHERE `block`.`isProcessed` = 1 ORDER BY `block`.`height` DESC LIMIT 1;'
akashlytics-api  |   },
akashlytics-api  |   sql: 'SELECT `height`, `datetime`, `dayId`, `isProcessed`, `totalTxCount`, `totalUAktSpent`, `activeLeaseCount`, `totalLeaseCount`, `activeCPU`, `activeMemory`, `activeStorage`, `activeProviderCount`, `createdAt`, `updatedAt` FROM `block` AS `block` WHERE `block`.`isProcessed` = 1 ORDER BY `block`.`height` DESC LIMIT 1;',
akashlytics-api  |   parameters: undefined
akashlytics-api  | }
akashlytics-web  | 172.19.0.1 - - [26/Apr/2022:12:02:41 +0000] "GET /favicon/site.webmanifest HTTP/1.1" 200 426 "http://127.0.0.1:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
```

Any idea how can I start Akashlytics locally / what am I missing? :)

**Comment by Redm4x** [comment]
Hi, when starting the app it is downloading the latest backup of the database first:
![image](https://user-images.githubusercontent.com/2829180/165318373-577f992f-fefe-4a6a-b6f3-a38a93e0f800.png)
You will see a `Database downloaded` log entry when it's done and it will then sync from there. It's a 3.9Gb file so it may take a while. If you try to access the app while it's downloading this backup you will get the `SQLITE_CORRUPT: database disk image is malformed` error.
